name: Deploy Website

on:
  push:
    branches:
      - main

jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

    steps:
    - name: Get latest code
      uses: actions/checkout@v4

    - name: Copy files via SFTP
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        port: 22
        source: "."
        target: "." # <--- IMPORTANT: Change this to your server's folder name
        rm: false             # Set to true if you want to delete old files first